name: Tests
on:
  push:
  # Scheduled runs ensure we are alerted to incompatibilities in new releases of
  # Go and Terraform.
  schedule:
    - cron: '0 10 * * 3'

jobs:

  #
  # Run unit tests
  #
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - ""  # Latest
          - "1.15"
          - "1.14"

    steps:

      # Install Go and Terraform
      - uses: actions/setup-go@v2
        with:
          go-version: '${{ matrix.go }}'

      # Checkout
      - uses: actions/checkout@v2

      # Restore cache
      - uses: actions/cache@v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-v${{ matrix.go }}-${{ hashFiles('**/go.sum') }}

      # Run unit tests
      - name: Unit tests
        run: go test -v -covermode=atomic -coverprofile=coverage.out ./...
